name: Build Marlin Firmware (Native)

on:
  push:
    branches: [ main, gha-native-build ]
    paths:
      - 'Configuration.h'
      - 'Configuration_adv.h'
      - '.github/workflows/build-firmware-native.yml'
      - 'platformio.ini'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Marlin source
      id: cache-marlin
      uses: actions/cache@v3
      with:
        path: MarlinSource
        key: marlin-2.1.2.5-source

    - name: Download Marlin source
      if: steps.cache-marlin.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/MarlinFirmware/Marlin.git MarlinSource
        cd MarlinSource
        git checkout 2.1.2.5
        # Remove the config files that we'll replace
        rm Marlin/Configuration.h Marlin/Configuration_adv.h

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: |
          ~/.platformio
          ~/.cache/pip
        key: platformio-lpc1768-${{ runner.os }}

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Copy configuration files
      run: |
        cp Configuration.h MarlinSource/Marlin/
        cp Configuration_adv.h MarlinSource/Marlin/
        echo "Configuration files copied to Marlin source"

    - name: Show configuration summary
      run: |
        echo "### Configuration Summary ###"
        echo "Board: $(grep '#define MOTHERBOARD' MarlinSource/Marlin/Configuration.h | awk '{print $3}')"
        echo "Bed Size: $(grep '#define X_BED_SIZE' MarlinSource/Marlin/Configuration.h | awk '{print $3}')x$(grep '#define Y_BED_SIZE' MarlinSource/Marlin/Configuration.h | awk '{print $3}')"
        echo "BLTouch: $(grep '^#define BLTOUCH' MarlinSource/Marlin/Configuration.h > /dev/null && echo 'Enabled' || echo 'Disabled')"
        echo "Auto Bed Leveling: $(grep '^#define AUTO_BED_LEVELING' MarlinSource/Marlin/Configuration.h | head -1 | awk '{print $2}')"
        echo "Serial Port: $(grep '^#define SERIAL_PORT ' MarlinSource/Marlin/Configuration.h | awk '{print $3}')"
        echo "Serial Port 2: $(grep '^#define SERIAL_PORT_2' MarlinSource/Marlin/Configuration.h | awk '{print $3}')"

    - name: Build firmware
      run: |
        cd MarlinSource
        platformio run -e LPC1768

        # Show build result
        echo "### Build Complete ###"
        ls -la .pio/build/LPC1768/firmware.bin
        md5sum .pio/build/LPC1768/firmware.bin

    - name: Copy firmware to workspace
      run: |
        cp MarlinSource/.pio/build/LPC1768/firmware.bin ./firmware.bin
        md5sum firmware.bin

    - name: Generate build info
      run: |
        echo "## Firmware Build Info" > build_info.txt
        echo "Build Date: $(date)" >> build_info.txt
        echo "Git Commit: ${{ github.sha }}" >> build_info.txt
        echo "Git Branch: ${{ github.ref_name }}" >> build_info.txt
        echo "" >> build_info.txt
        echo "### Configuration:" >> build_info.txt
        echo "- Board: MKS SBASE (LPC1768)" >> build_info.txt
        echo "- Marlin Version: 2.1.2.5" >> build_info.txt
        echo "- Bed Size: 194x205mm" >> build_info.txt
        echo "- X Offset: -15mm" >> build_info.txt
        echo "- Y Offset: -8mm" >> build_info.txt
        echo "- Probe: BLTouch (-24, -36, -3.7)" >> build_info.txt
        echo "- SD Card: ONBOARD (USB Mass Storage enabled)" >> build_info.txt
        echo "- Auto Bed Leveling: LINEAR (3x3 grid)" >> build_info.txt
        echo "" >> build_info.txt
        echo "### Features:" >> build_info.txt
        echo "- EEPROM Settings" >> build_info.txt
        echo "- Z Safe Homing" >> build_info.txt
        echo "- Babystepping" >> build_info.txt
        echo "- M600 Filament Change" >> build_info.txt
        echo "- Host Action Commands" >> build_info.txt
        echo "- Emergency Parser" >> build_info.txt
        echo "" >> build_info.txt
        echo "### Firmware Details:" >> build_info.txt
        echo "MD5: $(md5sum firmware.bin | cut -d' ' -f1)" >> build_info.txt
        echo "Size: $(stat -c%s firmware.bin) bytes" >> build_info.txt

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: marlin-firmware-${{ github.run_number }}
        path: |
          firmware.bin
          build_info.txt
          Configuration.h
          Configuration_adv.h
        retention-days: 90

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          firmware.bin
          build_info.txt
          Configuration.h
          Configuration_adv.h
        body: |
          ## Marlin Firmware for Monoprice Maker Select V2

          **Board:** MKS SBASE (LPC1768)
          **Marlin Version:** 2.1.2.5

          ### Features:
          - Corrected bed size: 194x205mm
          - Corrected X/Y offsets for proper bed alignment
          - BLTouch auto bed leveling (3x3 grid)
          - USB SD card support for OctoPrint updates
          - EEPROM settings persistence
          - M600 filament change support
          - TFT35 display support

          ### Installation:
          1. Copy `firmware.bin` to SD card root
          2. Insert SD card into printer
          3. Power cycle printer
          4. Firmware will auto-flash (file renamed to FIRMWARE.CUR when complete)
          5. Run `M502` then `M500` to load and save default settings

          ### Configuration Files:
          The Configuration.h and Configuration_adv.h files are included for reference.
        draft: false
        prerelease: false