name: Build Marlin Firmware

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-firmware.yml'
      - 'apply_marlin_config.sh'
      - 'gen_patch.sh'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build firmware with Docker
      run: |
        # Build the Docker image and compile firmware
        docker build --build-arg CACHE_DATE=$(date +"%m/%d-%H:%M") -t marlin .

        # Create container to extract firmware
        docker create --name marlin-container marlin

        # Copy firmware from container
        docker cp marlin-container:/Marlin/.pio/build/LPC1768/firmware.bin ./firmware.bin

        # Clean up
        docker rm marlin-container

        # Show firmware info
        ls -la firmware.bin
        md5sum firmware.bin

    - name: Generate build info
      run: |
        echo "## Firmware Build Info" > build_info.txt
        echo "Build Date: $(date)" >> build_info.txt
        echo "Git Commit: ${{ github.sha }}" >> build_info.txt
        echo "Git Branch: ${{ github.ref_name }}" >> build_info.txt
        echo "" >> build_info.txt
        echo "### Configuration:" >> build_info.txt
        echo "- Board: MKS SBASE (LPC1768)" >> build_info.txt
        echo "- Bed Size: 194x205mm" >> build_info.txt
        echo "- X Offset: -15mm" >> build_info.txt
        echo "- Y Offset: -8mm" >> build_info.txt
        echo "- SD Card: ONBOARD (USB Mass Storage enabled)" >> build_info.txt
        echo "" >> build_info.txt
        echo "### Firmware Details:" >> build_info.txt
        echo "MD5: $(md5sum firmware.bin | cut -d' ' -f1)" >> build_info.txt
        echo "Size: $(stat -c%s firmware.bin) bytes" >> build_info.txt

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: marlin-firmware-${{ github.run_number }}
        path: |
          firmware.bin
          build_info.txt
        retention-days: 90

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          firmware.bin
          build_info.txt
        body: |
          ## Marlin Firmware for Monoprice Maker Select V2

          **Board:** MKS SBASE (LPC1768)
          **Marlin Version:** 2.1.2.5

          ### Features:
          - Corrected bed size: 194x205mm
          - Corrected X/Y offsets for proper bed alignment
          - USB SD card support for OctoPrint updates
          - BLTouch support
          - Auto bed leveling

          ### Installation:
          1. Copy `firmware.bin` to SD card root
          2. Insert SD card into printer
          3. Power cycle printer
          4. Firmware will auto-flash (file renamed to FIRMWARE.CUR when complete)
        draft: false
        prerelease: false